### ISSUE TITLE
Just some ideas

### ISSUE THREAD

**Issue by benedekrozemberczki** [JamesOwers/midi_degradation_toolkit#108]
- Add labels optimized for search.
- Add a head logo.
- Add a preview image.

**Comment by JamesOwers** [comment]
Only just noticed this, thanks for comments!

What do you mean by 'labels' here? And preview image?! I'm presuming a head logo is just to make the readme look nice!

**Comment by benedekrozemberczki** [comment]
If you add labels to the repo online a larger number of GitHub search
queries will return it for users. By preview I mean that in Settings you
can add a social media preview.
