### ISSUE TITLE
Interrupting during ./make_dataset download step results in error

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#116]
If a zip file is incomplete, the following calls return BadZipfile exception. Even calling with --clear-download-cache does this. Only manually deleting the download cache fixes the issue.

**Comment by apmcleod** [comment]
I think we should add a --clean option that will clear the download cache and input_files directories (with y/n confirmation). The script would clean and then exits. It doesn't require running the full script again.

**Comment by JamesOwers** [comment]
@apmcleod - please may you outline exactly what to do to reproduce the error?

**Comment by JamesOwers** [comment]
Add the --clean flag, plus a useful catch for BadZipFile which directs you to use the flag!
