### ISSUE TITLE
Recreate acme

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#123]
#121 and #122 are big errors. We need to recreate acme with these fixed.

**Comment by apmcleod** [comment]
(Hopefully with a different seed, like 0 or 42 :) )

**Comment by apmcleod** [comment]
I believe that acme is ready to be re-created once the amt PR is merged. We should do some manual spot checks to confirm before starting the model re-training.

**Comment by JamesOwers** [comment]
tests will be implemented alongside #129
