### ISSUE TITLE
Create documentation notebooks

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#129]
* Documentation notebooks:
    * the data and degradation functions
    * dataset creation
    * the acme dataset
    * the degrader
    * measure errors
    * the models (load parameters saved on dropbox)
    * evaluation
    * reproducing results

**Comment by apmcleod** [comment]
Probably can be closed?

**Comment by JamesOwers** [comment]
Yup!
