### ISSUE TITLE
The overlap check in read_note_csv is dog slow...

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#24]
The line `df = df.groupby(['track', 'pitch']).apply(fix_overlapping_notes)` increases computation time by at least 100x. This is mad. For now, I'm just going to bypass this by adding a flag to skip the check (we decided not to enforce this), but I think we will learn something if we try to profile the code and understand why it's so slow.

**Comment by apmcleod** [comment]
Closing as #64 is a more updated version of this issue.
