### ISSUE TITLE
df_to_csv and csv_to_df should probably be in the same place

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#33]
I'd go for having them both in that "midi" package and renaming it perhaps? (Currently csv_to_df is data_structures.read_note_csv)

Essentially, mdtk.midi (renamed) would be for file I/O and conversion, while mdtk.data_structures would be about doing things with dataframes.

**Comment by JamesOwers** [comment]
Kicking this to camera ready as it will not affect functionality for ACME v1.0 creation

**Comment by JamesOwers** [comment]
Move read_note_csv from data_structures to midi.csv_to_df. Rename midi to fileio.
