### ISSUE TITLE
Investigate use of `inplace` operations for efficiency in degradations

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#35]
Whilst it's not possible to operate inplace when adding new data to dataframes (a copy must occur), there are various degradations that could work inplace - this could be much more efficient if the user doesn't want to retain the original dataframe.

Investigate speedups obtained and whether this is worth it.

**Comment by apmcleod** [comment]
inplace=True seems to make no difference in performance for those degradations which don't necessitate copies. This is odd.
