### ISSUE TITLE
Enforce DataFrame formatting

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#37]
Or, add tests in the degradations with other formats.

For example, there are currently no tests with dataframes without consecutive indices starting from 0, or unsorted dataframes, or ones with columns out of order.

Some of these we might want to allow, some we might be okay with errors.

We could also add a function which, given some data frame, enforces formatting, like:
1. Drops all columns not pitch, onset, offset, track
2. Rounds those columns to ints
3. Puts those columns in the correct order
4. Sorts the dataframe
5. Reset the index in that order and drop the index column

Currently, the degradations are closed under 1, 2, 3, and 5 (if given correctly, will return correctly), but not necessarily 4 (the resulting df may not be sorted, even if the input one was).

Giving one a df which has the wrong columns would likely error.

**Comment by apmcleod** [comment]
I've also just realized, it is probably the case that join_notes will fail to find some possible notes to join if the input dataframe is not sorted correctly.

Given this, we can either sort within join_notes, or give a method to enforce the properties we want on a df, and say that unexpected things may happen if it's not done correctly. (I think the latter is fine). If we choose that, we'll want to ensure the df is sorted correctly after each degradation (perhaps with that function).

Like:
```
def fix_df(df, sort=True, columns=True, round=True, order_columns=True, reset_index=True):
```
and this would do whichever we choose.

**Comment by apmcleod** [comment]
Update: On the current degradations branch, degradations:

1. Always return a correctly sorted dataframe with consecutive indices starting from 0.
2. Always work given dataframes with non-consecutive indices.

They don't :
1. Check if the given df is sorted (and may err).
2. Check that the given df has the correct columns and column-ordering (and may err).
3. Check that the given df contains only ints (and may err).
4. Check for any duplicate indices in the df (and may err).

My opinion:
1. Given that we post-sort anyways now, we should probably pre-sort the df for any degradation that might fail on an unsorted df.
2. If a given df doesn't contain all of the columns we need, we should raise an exception.
3. If a given df has extra columns, we can ignore them and add Nans (or whatever is pandas default) to those if we add new notes.
4. If a given df's columns are in the wrong order, we should re-order them on input, pushing any extra columns (treated as in 3) to the end. Then, we can re-order the columns back to the original ordering on return?
5.If the given df contains non-integer values, we should raise an exception.
6. If the given df contains duplicate indices, we should reset the indices (since we will do so in post-processing anyways).

**Comment by apmcleod** [comment]
Now, being given unsorted dfs, or dfs with non-consecutive or duplicate indices is always fine and always returns a sorted df with consecutive indices starting from 0.

TODO:
1. Decide how to handle non-integers
2. Decide how to handle incorrect or out of order columns.

**Comment by apmcleod** [comment]
Now the only thing left is to decide how to dfs which don't contain all of the columns we need. I am fine with just erring in the default ugly way in that case.

At the moment, you get an exception from pre_process:

```
ValueError: Cannot convert non-finite values (NA or inf) to integer
```

And the following warning:
```
Warning: 
  Passing list-likes to .loc or [] with any missing label will raise
  KeyError in the future, you can use .reindex() as an alternative.
```

**Comment by JamesOwers** [comment]
So, the only case where this will happen is if someone provides their own data, or if they make their own downloader, is that correct? If that's the case, perhaps some initial checks at that stage would mean we dont have to do all these checks and sorts before degradations (but leave the option for checking in, should the user want to use deg functions standalone).

**Comment by apmcleod** [comment]
Mainly, these are in for users doing standalone degradations, which should be a reasonable clump of users, I hope. If people make their own downloaders, we can assume they will know enough to find the correct format (and it should be in the readme).

I would like the most naive user to get a definitely correct result (so leave checking on by default), but we could add a `validate_input=True` or `check=True` param to each that advanced users can set to False if they promise that their input will be well-formatted. Then, we can call them all with `check=False` in the make dataset script.

Important is that only the pre_processing is really optional. The post_processing is important always, really (unless the user explicitly doesn't care about it, but I'd not add that option unless someone requests it).

**Comment by JamesOwers** [comment]
> I would like the most naive user to get a definitely correct result (so leave checking on by default), but we could add a `validate_input=True` or `check=True` param to each that advanced users can set to False if they promise that their input will be well-formatted. Then, we can call them all with `check=False` in the make dataset script.

I agree with this. I don't think this is urgent, however. It works how the only users (you and me!) want it to just now for ACME v1.0 release. I'm going to kick this issue to the next milestone if that's ok with you. If not, put it back and I'll fix.

**Comment by JamesOwers** [comment]
We resolved to error if there are issues with the user provided csvs or dfs - check this is how we currently perform then close
