### ISSUE TITLE
Adapt `make_dataset.py` such that you can supply a flag to make it do just single parts

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#55]
At the moment, if you run the script without --command there's no way to create the command csvs without running the whole shebang again. We should think about how best to do structure the script to make stuff like this easier.

**Comment by apmcleod** [comment]
In models, this is now moved to a new function here: https://github.com/JamesOwers/midi_degradation_toolkit/blob/models/mdtk/pytorch_datasets.py#L57

Not callable via script, though.

**Comment by apmcleod** [comment]
Fixed by #62
