### ISSUE TITLE
Fix the pip install

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#65]
Hopefully this wont be too hard. Essentially I'd like the default setting to install bare minumum, and an -all type flag to install full optional dependencies. Don't know the standard for that but need to sort it for ease.

**Comment by apmcleod** [comment]
Yes, love this! And hopefully the ability to go from default to --all easily with pip too.

**Comment by JamesOwers** [comment]
Weirdly the pip install no longer works for me at all!

```
(mdtk) [charles01]s0816700: pip install -e ./
Obtaining file:///mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit
    ERROR: Command errored out with exit status 1:
     command: /home/s0816700/miniconda3/envs/mdtk/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit/setup.py'"'"'; __file__='"'"'/mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /mnt/cdtds_cluster_home/s0816700/git/midi_degradation_toolkit/
    Complete output (5 lines):
    running egg_info
    writing mdtk.egg-info/PKG-INFO
    /home/s0816700/miniconda3/envs/mdtk/lib/python3.7/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '2019.06rc1' to '2019.6rc1'
      normalized_version,
    error: [Errno 22] Invalid argument
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

BUT running  `python setup.py install` does 🤷‍♂

**Comment by JamesOwers** [comment]
Also - add mir_eval to optional deps

**Comment by JamesOwers** [comment]
This is fixed by https://github.com/JamesOwers/midi_degradation_toolkit/commit/bc64f2fd4c348a29f51340af9e8bd5d1b20a49c2. I have tested on Linux and Unix, but not windows. @apmcleod - do you have ability to test on a windows machine? All that's required is trying to run the following:
```
git clone https://github.com/JamesOwers/midi_degradation_toolkit
cd midi_degradation_toolkit
conda create -y -n mdtk python=3.7
conda activate mdtk
pip install .
./make_dataset.py
```

If that runs with no problem then we're good.

**Comment by apmcleod** [comment]
I'll try. There's no `cd` command, for example, but I can write some instructions if I get it to work.

**Comment by JamesOwers** [comment]
Ah sure, that's `dir` right?! TBH there's a limit to how much support I
think is reasonable to provide (I would kind of expect windows users to
quickly be able to google that one!).

**Comment by apmcleod** [comment]
Fully agree
