### ISSUE TITLE
Add dataloader to degrade on the fly

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#82]
To allow essentially unlimited training data from a limited set of MIDI files.

This will enable people to train VAEs, AMT models, etc on the fly from a limited dataset.

**Comment by JamesOwers** [comment]
json pased to this much like the one passed to make_dataset

**Comment by apmcleod** [comment]
This is really fixed by the Degrader in #119. If you agree, close this issue.
