### ISSUE TITLE
Decide which scripts, etc to include in the mdtk package

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#83]
Probably most/all of them? But we should think about exactly what functionality the end-user would want.

**Comment by JamesOwers** [comment]
I reference this in https://github.com/JamesOwers/midi_degradation_toolkit/pull/79 latest comment. In my opinion, for now, we just expect people to:
1. clone the repo
2. pip install as the "setup" step to get code in the repo to work i.e. all this really does is makes all `import mdtk...` references in code work (and imports of required packages)

At a later date we can think about releasing scripts with the package, but for now I like this setup as it's more explicit for users. Pip installing mdtk with scripts will hide away readme files and other stuff, requiring us to make some sort of documentation website.

**Comment by apmcleod** [comment]
That seems reasonable to me. Will think about this.
