### ISSUE TITLE
Ensure constant file ordering in make dataset

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#89]
Specifically here: https://github.com/JamesOwers/midi_degradation_toolkit/blob/f2a2712bad693062f47594b706f5b6742966873f/make_dataset.py#L348

Glob doesn't enforce any ordering, so different people will get the csvs I'm different orders. We need to add a `sorted` to this line. I've had this problem before.

**Comment by JamesOwers** [comment]
fixed:
https://github.com/JamesOwers/midi_degradation_toolkit/blob/1d9255c09c5c64ca6284f0ff040aa461c1d98b47/make_dataset.py#L354
