### ISSUE TITLE
Remove corpus base path from format_csv_paths

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#92]
When we create formats, we add a field (e.g.) "cmd_corpus_path" to metadata.csv.

This field should contain the path to cmd_corpus.csv (or whatever we call it), in relation to the base acme output dir. However, currently it contains the acme dir name in the value, e.g. `acme/cmd_corpus.csv` instead of simply `cmd_corpus.csv`.

This causes a diff between 2 identical corpora in different directories.

I don't think we actually read this value elsewhere ever, but it would be worth checking that to be sure once this is changed.

**Comment by JamesOwers** [comment]
https://github.com/JamesOwers/midi_degradation_toolkit/commit/36751bceeffe43c5a3a6749a4bd4ce2fe860e474

This commit *should* fix this. I'm re-running everything now, but please may you just quickly look over the other commits: I renamed variables as it wasn't clear what 'splits' and 'props' were referring to (sometimes it was about the degradations, other times it was the trainvaltest splits). I've renamed things to make clearer and rerunning to test now, but good for you to look over and check names match your intention.

**Comment by apmcleod** [comment]
Looks like that should fix it but I can't check. Var names also look correct.

**Comment by JamesOwers** [comment]
Ok, scripts are running fine so I'm going to presume I didn't mess up 😂
