### ISSUE TITLE
In mdtk.degradations function overlaps, the var offsets is unused

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#95]
The line in question is this:

https://github.com/JamesOwers/midi_degradation_toolkit/blob/f2a2712bad693062f47594b706f5b6742966873f/mdtk/degradations.py#L75

**Comment by apmcleod** [comment]
This is fine to remove. It looks like I just called that addition manually in the following line, since it is only done once.

The overlaps function is included in the tests, so it works fine as is.
